apiVersion: v1
kind: Secret
metadata:
  name: minio-storage-configuration
  namespace: photoatom-object-storage
  labels:
    app: minio
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="CONFIG_MINIO_ROOT_USER"
    export MINIO_ROOT_PASSWORD="CONFIG_MINIO_ROOT_PASSWORD"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
