apiVersion: v1
kind: Secret
metadata:
  name: minio-storage-user
  namespace: photoatom-object-storage
  labels:
    app: minio
type: Opaque
data:
  CONSOLE_ACCESS_KEY: CONFIG_CONSOLE_ACCESS_KEY
  CONSOLE_SECRET_KEY: CONFIG_CONSOLE_SECRET_KEY
